name: BIST Tüm Cloud Tarama ve GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu al
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bağımlılıkları yükle
        run: npm install

      - name: Projeyi derle
        run: npm run build

      - name: GitHub Pages’a dağıt
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
